# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufs', '0002_auto_20171026_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
    ]
