# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ufs', '0006_auto_20171027_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 27, 6, 55, 48, 533158, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Images',
            field=models.CharField(default=datetime.datetime(2017, 10, 27, 6, 56, 3, 816216, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
