# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ufs', '0008_auto_20171027_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='First_seen',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 8, 48, 0, 467539, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
