# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customercorner', '0015_auto_20171024_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prize', models.IntegerField()),
                ('Quality', models.CharField(max_length=15)),
                ('Description', models.CharField(max_length=150)),
                ('Min_order', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
