# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0015_auto_20171024_0605'),
        ('shop', '0005_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=15)),
                ('Service_name', models.CharField(max_length=20)),
                ('Product', models.ManyToManyField(to='customercorner.Product')),
            ],
        ),
    ]
