# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20171027_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Min_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='Quality',
            field=models.CharField(max_length=150),
        ),
    ]
