# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(choices=[(b'SUM', b'Summer'), (b'WIN', b'Winter')], max_length=5)),
            ],
        ),
    ]
