# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0003_preproductinfo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='preproductinfo',
            name='Soil_type',
            field=models.CharField(choices=[(b'sum', b'Summer'), (b'win', b'Winter')], default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='preproductinfo',
            name='Season',
            field=models.CharField(choices=[(b'sum', b'Summer'), (b'win', b'Winter')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_type',
            field=models.CharField(choices=[(b'dairy', b'Dairy Product'), (b'fruits', b'Fruits'), (b'veg', b'Vegetables')], max_length=15),
        ),
    ]
