# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0006_auto_20171021_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproductinfo',
            name='Soil_type',
            field=models.CharField(choices=[(b'alluvial', b'Alluvial'), (b'loamy', b'Loamy')], default=None, max_length=10),
        ),
    ]
