# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0007_auto_20171021_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproductinfo',
            name='Season',
            field=models.CharField(choices=[(b'summer', b'Summer'), (b'winter', b'Winter')], default=None, max_length=10),
        ),
    ]
