# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0008_auto_20171021_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadQualityCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckingConditions', models.TextField(help_text=b"Please seprate the Good Conditions of the Product by comma's", max_length=1500)),
                ('Select_Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
            ],
        ),
        migrations.CreateModel(
            name='GoodQualityCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckingConditions', models.TextField(help_text=b"Please seprate the Good Conditions of the Product by comma's", max_length=1500)),
                ('Select_Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
            ],
        ),
        migrations.CreateModel(
            name='NutrionalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NutrionalData', models.TextField(help_text=b"Please seprate the Nutrional Content by comma's", max_length=1500)),
                ('ConsumptionEffect', models.TextField(help_text=b"Please seprate the Consumption Effect by comma's", max_length=1500)),
                ('Select_Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='preproductinfo',
            name='Season',
            field=models.CharField(choices=[(b'Summer', b'Summer'), (b'Winter', b'Winter')], default=None, max_length=10),
        ),
    ]
