# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0011_auto_20171023_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='badqualitycondition',
            name='Good_Images',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodqualitycondition',
            name='Good_Images',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrionalcontent',
            name='NutrionChart',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preproductinfo',
            name='Product_Images',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
