# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0013_auto_20171023_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product_type'),
        ),
    ]
