# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0016_cultivationmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivationmethods',
            name='Select_Product',
        ),
        migrations.AddField(
            model_name='cultivationmethods',
            name='Select_Product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product'),
            preserve_default=False,
        ),
    ]
