# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20171027_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidding_Price', models.IntegerField()),
                ('sample', models.BooleanField()),
                ('Query', models.CharField(max_length=150)),
                ('Auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Auction')),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
