# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20171027_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
