# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
