# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customercorner', '0012_auto_20171023_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preproductinfo',
            name='Product_Images',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Images',
            field=models.ImageField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
