# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customercorner', '0015_auto_20171024_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ufs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('Description', models.CharField(max_length=1500)),
                ('Images', models.ImageField(upload_to=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('effected_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
            ],
        ),
    ]
