# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customercorner', '0015_auto_20171024_0605'),
        ('ufs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('Description', models.CharField(max_length=1500)),
                ('Images', models.ImageField(upload_to=b'')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('effected_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customercorner.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='ufs',
            name='effected_crop',
        ),
        migrations.DeleteModel(
            name='ufs',
        ),
    ]
