# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufs', '0004_auto_20171027_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
