# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufs', '0007_auto_20171027_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Images',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
